### ISSUE TITLE
Colored box in upper left corner in grid view

### ISSUE THREAD

**Issue by GodSponge** [Lacro59/playnite-defaultextend-theme#5]
Suddenly, with the most recent update of the theme, I get a box in the upper left of the boxart in grid view (seems to be age rating of some kind). This was not there in the previous version. I have tried to find some kind of setting for this, but the constants page only shows "Visible" or "Collapsed" for age rating icons. When set to visible, I can see the actual ratings icons UNDER the colored box (the box sits in front of the ratings icons). When set to collapsed, all I see is the box. I honestly don't mind the actual age rating icons, its the colored boxes that I can't seem to get rid of. Is this a bug? If it's a feature, is there a way to turn it off? 
![example](https://user-images.githubusercontent.com/20741982/207996673-cc447477-b919-4148-99e7-afa472b3fa69.png)

**Comment by Lacro59** [comment]
This box is a new element of the LibrayManagement plugin.
You can disable this in the plugin settings on the appearance tab.
![image](https://user-images.githubusercontent.com/124054/208054321-1900d5a0-273b-4b55-844c-6ee937cb71ce.png)

**Comment by GodSponge** [comment]
Well that would be why I couldn't find it. That page has a checkbox, but no text next to it on my Playnite. Not sure what's going on there. 
![Playnite DesktopApp_8wwcwymEig](https://user-images.githubusercontent.com/20741982/208184328-7f7d9cfd-2efc-40ff-b758-9311332b485b.png)

Thank you so much! this was driving me crazy!
