### ISSUE TITLE
Feature request to disable visibility of some icons

### ISSUE THREAD

**Issue by arandomguysomewhere** [Lacro59/playnite-defaultextend-theme#8]
I really like this theme but there is some information showing up that I find distracting and would prefer to disable:
Grid view:
![image](https://github.com/Lacro59/playnite-defaultextend-theme/assets/633445/92274a6b-d6ae-4ec6-b206-7a5f585cb867)

Details view:
![image](https://github.com/Lacro59/playnite-defaultextend-theme/assets/633445/027da45c-7585-4bd8-9ab3-f8712d4dda0d)

Those crosses and not played fields are very distracting and don't fit my use cases, would it please be possible to have an option to disable them (as well as the grid view howlongtobeat icons)?

**Comment by Lacro59** [comment]
With [ThemeModifier](https://playnite.link/addons.html#playnite-thememodifier-plugin), you have many options for the theme:
![image](https://github.com/Lacro59/playnite-defaultextend-theme/assets/124054/b5cc9e11-aa63-4b04-a91b-3526b2b599d2)

[HowLongToBeat](https://playnite.link/addons.html#playnite-howlongtobeat-plugin) has an option for this:
![image](https://github.com/Lacro59/playnite-defaultextend-theme/assets/124054/185f58cb-c921-426b-ac5e-e54544db66b3)
